// app/terms/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import {
  FileText,
  ShieldCheck,
  Ban,
  Scale,
  Repeat,
  Mail,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service – DigitalMeve",
  description:
    "Clear and transparent rules for using DigitalMeve. DigitalMeve is not legal advice and is not, by itself, a legally binding proof.",
};

const LAST_UPDATED = "2025-09-25"; // TODO: update when you materially change the Terms

export default function TermsPage() {
  const sections = [
    { id: "acceptance", title: "Acceptance" },
    { id: "use", title: "Use of the service" },
    { id: "disclaimer", title: "No legal advice — Not a legal proof by itself" }, // moved up for visibility
    { id: "liability", title: "Limitations of liability" },
    { id: "termination", title: "Suspension & termination" },
    { id: "changes", title: "Changes" },
    { id: "governing-law", title: "Governing law & jurisdiction" }, // new
    { id: "definitions", title: "Definitions" }, // new
    { id: "contact", title: "Contact" },
    { id: "annex", title: "Annex — Legal context by jurisdiction" }, // rename of your previous block
  ];

  return (
    <main className="min-h-screen bg-[var(--bg)] text-[var(--fg)]">
      {/* HEADER */}
      <section className="border-b border-[var(--border)] bg-[var(--bg)]">
        <div className="container-max px-4 py-14">
          <div className="flex items-center gap-2">
            <FileText className="h-6 w-6 text-[var(--accent-2)]" />
            <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
              Terms of Service
            </h1>
          </div>
          <p className="mt-2 sub">The rules that govern your use of DigitalMeve.</p>
          <p className="mt-1 text-sm text-[var(--fg-muted)]">
            Last updated: <time dateTime={LAST_UPDATED}>{LAST_UPDATED}</time>
          </p>

          {/* TOC */}
          <nav className="mt-6 flex flex-wrap gap-2">
            {sections.map((s) => (
              <a
                key={s.id}
                href={`#${s.id}`}
                className="inline-flex items-center gap-2 rounded-full bg-white/5 px-3 py-1.5 text-xs font-medium text-[var(--fg-muted)] ring-1 ring-[var(--border)] hover:text-[var(--fg)]"
              >
                <span>{s.title}</span>
              </a>
            ))}
          </nav>
        </div>
      </section>

      {/* CONTENT */}
      <section className="section-dark">
        <div className="container-max px-4 py-12 space-y-10">
          <Card
            id="acceptance"
            icon={<ShieldCheck className="h-6 w-6 text-[var(--accent-1)]" />}
            title="1) Acceptance"
          >
            By using DigitalMeve, you agree to these Terms. If you do not agree, please do not use the service.
          </Card>

          <Card
            id="use"
            icon={<FileText className="h-6 w-6 text-[var(--accent-1)]" />}
            title="2) Use of the service"
          >
            You are solely responsible for the content you process. Do not use DigitalMeve for unlawful purposes, to infringe intellectual property rights, or to distribute harmful material.
          </Card>

          {/* 3) No legal advice / not a legal proof by itself */}
          <div id="disclaimer" className="card p-6 scroll-mt-24">
            <div className="flex items-center gap-2">
              <ShieldCheck className="h-6 w-6 text-[var(--accent-1)]" />
              <h2 className="h2">3) No legal advice — Not a legal proof by itself</h2>
            </div>

            <p className="mt-2 text-[var(--fg-muted)]">
              DigitalMeve is <b>not a law firm</b>, does <b>not</b> provide legal advice, and is <b>not</b> a substitute for legal counsel.
              Any “proof” or verification artifact generated by DigitalMeve <b>does not, by itself, constitute legally binding evidence</b>.
              Admissibility and legal weight depend on applicable laws, the facts of the case, and judicial assessment. Consult a qualified attorney for legal matters.
            </p>

            <p className="mt-2 text-[var(--fg-muted)]">
              DigitalMeve is <b>not</b> a Qualified Trust Service Provider (QTSP) and <b>does not issue</b> Qualified Electronic Signatures (QES).
              If your use case requires a QES, a notarial act, or other statutory formalities, you must use an appropriate legally recognized method.
            </p>
          </div>

          <Card
            id="liability"
            icon={<Scale className="h-6 w-6 text-[var(--accent-1)]" />}
            title="4) Limitations of liability"
          >
            The service is provided <em>“as is”</em> and <em>“as available”</em> without warranties of any kind. To the extent permitted by law,
            DigitalMeve disclaims all warranties and liability for damages arising from your use of the service.
          </Card>

          <Card
            id="termination"
            icon={<Ban className="h-6 w-6 text-[var(--accent-1)]" />}
            title="5) Suspension & termination"
          >
            We may suspend or terminate your access if you misuse the service or breach these Terms. We will make reasonable efforts to notify you in advance unless immediate action is required.
          </Card>

          <Card
            id="changes"
            icon={<Repeat className="h-6 w-6 text-[var(--accent-1)]" />}
            title="6) Changes"
          >
            We may update these Terms from time to time. If changes are significant, we will highlight them on this page or notify you directly.
          </Card>

          <Card
            id="governing-law"
            icon={<Scale className="h-6 w-6 text-[var(--accent-1)]" />}
            title="7) Governing law & jurisdiction"
          >
            These Terms are governed by <b>TODO: choose your governing law</b> (e.g., France / EU law). Any dispute shall be submitted to the
            <b> TODO: competent courts</b> (e.g., Paris, France), unless a different mandatory jurisdiction applies.
          </Card>

          <Card
            id="definitions"
            icon={<FileText className="h-6 w-6 text-[var(--accent-1)]" />}
            title="8) Definitions"
          >
            <b>“Proof” / “verification artifact”</b>: technical data (e.g., cryptographic fingerprint, timestamp, markers) helping to check integrity and authorship.
            <br />
            <b>“On-device processing”</b>: processing designed to run on your device; files are not intended to be stored on our servers.
          </Card>

          <Card
            id="contact"
            icon={<Mail className="h-6 w-6 text-[var(--accent-1)]" />}
            title="9) Contact"
          >
            For any questions, reach us at{" "}
            <a href="mailto:legal@digitalmeve.com" className="link">
              legal@digitalmeve.com
            </a>
            . For privacy matters, see our{" "}
            <Link href="/privacy" className="link">
              Privacy Policy
            </Link>
            .
          </Card>

          {/* 10) Annex — Legal context by jurisdiction */}
          <div id="annex" className="card p-6 scroll-mt-24">
            <div className="flex items-center gap-2">
              <ShieldCheck className="h-6 w-6 text-[var(--accent-1)]" />
              <h2 className="h2">10) Annex — Legal context by jurisdiction</h2>
            </div>

            <p className="mt-2 text-[var(--fg-muted)]">
              The following is provided for general information only and does not constitute legal advice.
              Requirements vary widely across jurisdictions; consult qualified counsel for your specific case.
            </p>

            <div className="mt-4 space-y-5 text-[var(--fg-muted)] text-sm">
              {/* EU / France */}
              <div>
                <h3 className="font-semibold text-[var(--fg)]">🇪🇺 European Union / France</h3>
                <p>
                  Only a <b>Qualified Electronic Signature (QES)</b> issued by a{" "}
                  <a
                    href="https://webgate.ec.europa.eu/tl-browser/#/"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    Qualified Trust Service Provider
                  </a>{" "}
                  benefits from automatic equivalence with handwritten signatures (Art. 25{" "}
                  <a
                    href="https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX%3A32014R0910"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    eIDAS Regulation
                  </a>, EU 910/2014). See also French Civil Code{" "}
                  <a
                    href="https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000032000411"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    Articles 1366–1367
                  </a>
                  . DigitalMeve does not issue QES and therefore cannot guarantee such equivalence.
                </p>
              </div>

              {/* US */}
              <div>
                <h3 className="font-semibold text-[var(--fg)]">🇺🇸 United States</h3>
                <p>
                  Under the{" "}
                  <a
                    href="https://www.govinfo.gov/content/pkg/PLAW-106publ229/pdf/PLAW-106publ229.pdf"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    ESIGN Act (2000)
                  </a>{" "}
                  and{" "}
                  <a
                    href="https://www.uniformlaws.org/committees/community-home?CommunityKey=2c04b76c-2b7d-4392-85b9-44c8c58e3a1a"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    UETA
                  </a>
                  , electronic signatures are valid if they show intent and consent. DigitalMeve proofs may support evidence, but they{" "}
                  <b>do not replace notarization</b> nor statutory formalities required for certain acts (e.g. real estate, wills).
                </p>
              </div>

              {/* UK */}
              <div>
                <h3 className="font-semibold text-[var(--fg)]">🇬🇧 United Kingdom</h3>
                <p>
                  Electronic signatures are recognized under the{" "}
                  <a
                    href="https://www.legislation.gov.uk/ukpga/2000/7/contents"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    Electronic Communications Act 2000
                  </a>
                  . Guidance from the{" "}
                  <a
                    href="https://www.lawcom.gov.uk/project/electronic-execution-of-documents/"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    Law Commission
                  </a>{" "}
                  confirms validity, but some acts may still require a witness or notary.
                </p>
              </div>

              {/* Canada */}
              <div>
                <h3 className="font-semibold text-[var(--fg)]">🇨🇦 Canada</h3>
                <p>
                  Electronic signatures are governed by{" "}
                  <a
                    href="https://laws-lois.justice.gc.ca/fra/lois/P-8.6/"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    PIPEDA
                  </a>{" "}
                  and provincial laws (e.g. Ontario Electronic Commerce Act). Proofs may be admissible, but certain transactions
                  (e.g. land transfers) require specific legal forms.
                </p>
              </div>

              {/* Other jurisdictions */}
              <div>
                <h3 className="font-semibold text-[var(--fg)]">🌍 Other jurisdictions</h3>
                <p>
                  Many countries follow the{" "}
                  <a
                    href="https://uncitral.un.org/en/texts/ecommerce/modellaw/electronic_commerce"
                    target="_blank"
                    rel="noopener noreferrer nofollow"
                    className="link"
                  >
                    UNCITRAL Model Law on Electronic Commerce
                  </a>
                  . However, requirements vary widely. Users must verify compliance with their local laws. DigitalMeve provides{" "}
                  <b>no guarantee of statutory equivalence</b>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FOOTER CTA */}
      <section className="border-t border-[var(--border)] bg-[var(--bg)]">
        <div className="container-max px-4 py-10 text-center">
          <p className="text-sm text-[var(--fg-muted)]">
            Questions about our Terms?{" "}
            <Link href="/contact" className="link font-medium">
              Contact us
            </Link>
            .
          </p>
        </div>
      </section>
    </main>
  );
}

/* ------------ UI bits ------------ */

function Card({
  id,
  icon,
  title,
  children,
}: {
  id: string;
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div id={id} className="card p-6 scroll-mt-24">
      <div className="flex items-center gap-2">
        {icon}
        <h2 className="h2">{title}</h2>
      </div>
      <p className="mt-2 text-[var(--fg-muted)]">{children}</p>
    </div>
  );
}
