// lib/proof-html.ts
import { stringifyCanonical } from "@/lib/proof";

export type ProofShape = Record<string, any>;

export function buildProofHtml(proof: ProofShape): string {
  const canonical = stringifyCanonical(proof);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>DigitalMeve Proof</title>
  <style>
    body { font-family: system-ui, sans-serif; background: #0B1220; color: #E5E7EB; margin: 0; padding: 2rem; }
    .card { max-width: 800px; margin: auto; background: #111827; border-radius: 1rem; padding: 2rem; border: 1px solid #1F2937; }
    h1 { font-size: 1.5rem; color: #10B981; margin-bottom: 1rem; }
    pre { background: #1F2937; padding: 1rem; border-radius: .75rem; overflow-x: auto; font-size: 0.875rem; }
    .meta { margin-top: 2rem; font-size: 0.75rem; color: #9CA3AF; text-align: center; }
    code { color: #93C5FD; }
  </style>
</head>
<body>
  <div class="card">
    <h1>✅ DigitalMeve Proof</h1>
    <p>This document contains a signed <code>.MEVE</code> proof generated by DigitalMeve.</p>
    <pre>${canonical}</pre>
    <div class="meta">
      Generated by <strong>DigitalMeve</strong> — <a href="https://digitalmeve.com" style="color:#10B981">digitalmeve.com</a>
    </div>
  </div>
</body>
</html>`;
}
