// lib/proof-html.ts
export function buildProofHtml(proof: any) {
  const S = (v: any) =>
    typeof v === "string" ? v.replace(/[&<>"]/g, s => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[s]!)) : String(v ?? "");

  const doc = proof?.doc ?? {};
  const iss = proof?.issuer ?? {};
  const created = proof?.created_at ?? "";
  const version = proof?.version ?? "meve/1";

  const rows = (obj: Record<string, any>) => {
    const entries = Object.entries(obj).filter(([, v]) => v !== undefined && v !== null && v !== "");
    if (!entries.length) return `<div class="mut">No details provided.</div>`;
    return entries.map(([k, v]) => `
      <div class="row">
        <div class="k">${S(k)}</div>
        <div class="v">${S(v)}</div>
      </div>
    `).join("");
  };

  const raw = JSON.stringify(proof); // on insérera dans <code> via JS

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>DigitalMeve Proof</title>
<style>
:root{--bg:#0b1220;--card:#0f172a;--mut:#94a3b8;--txt:#e2e8f0;--em:#34d399;--ln:#38bdf8}
*{box-sizing:border-box}html,body{height:100%}
body{margin:0;background:var(--bg);color:var(--txt);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial}
.wrap{max-width:1100px;margin:0 auto;padding:28px}
.header{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}
.badge{font-size:12px;color:#10b981;background:rgba(16,185,129,.12);border:1px solid rgba(16,185,129,.3);padding:4px 10px;border-radius:999px}
.h1{font-size:22px;margin:0}
.card{background:linear-gradient(180deg,rgba(255,255,255,.02),transparent),var(--card);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:22px}
.sub{color:var(--mut);margin:6px 0 16px 0}
.grid{display:grid;gap:16px}
@media(min-width:900px){.grid{grid-template-columns:1fr 1fr}}
.section{border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:14px}
.section h2{margin:0 0 10px 0;font-size:15px;color:#cbd5e1}
.row{display:grid;grid-template-columns:180px 1fr;gap:10px;padding:8px 0;border-top:1px dashed rgba(255,255,255,.08)}
.row:first-child{border-top:0}
.k{color:#a8b1c2}
.v{word-break:break-all}
code{background:rgba(255,255,255,.06);padding:2px 6px;border-radius:6px}
pre{white-space:pre-wrap;word-break:break-word;background:rgba(0,0,0,.25);padding:12px;border-radius:8px;border:1px solid rgba(255,255,255,.08);max-height:420px;overflow:auto}
a{color:var(--ln);text-decoration:none}
.mut{color:var(--mut)}
.foot{margin-top:14px;color:var(--mut);font-size:12px}
</style>
</head>
<body>
  <div class="wrap">
    <div class="header">
      <div class="badge">DigitalMeve · .MEVE proof</div>
      <div class="mut">Version: ${S(version)}</div>
    </div>

    <div class="card">
      <h1 class="h1">Document proof</h1>
      <div class="sub">Human-readable rendering of a .MEVE proof. The canonical JSON is included below.</div>

      <div class="grid">
        <div class="section">
          <h2>Document</h2>
          ${rows({
            Name: doc.name,
            MIME: doc.mime,
            Size: typeof doc.size === "number" ? `${doc.size} bytes` : undefined,
            "SHA-256": doc.sha256
          })}
        </div>

        <div class="section">
          <h2>Issuer</h2>
          ${rows({
            Name: iss.name,
            Identity: iss.identity,
            Type: iss.type,
            Website: iss.website,
            "Domain verified": iss.verified_domain === true ? "yes" :
                               iss.verified_domain === false ? "no" : undefined
          })}
        </div>
      </div>

      <div class="section" style="margin-top:16px">
        <h2>Raw canonical JSON</h2>
        <pre><code id="json"></code></pre>
      </div>

      <div class="foot">
        Created at: ${S(created)} · Generated by <a href="https://digitalmeve.com" target="_blank" rel="noopener">DigitalMeve</a>
      </div>
    </div>
  </div>
  <script>
    const raw = ${JSON.stringify(raw)};
    document.getElementById('json').textContent = raw;
  </script>
</body>
</html>`;
}
